/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Empresa;

/**
 *
 * @author Barbero
 */
public class Administrador extends javax.swing.JFrame {
    
    Empresa miEmpresa;

    /**
     * Creates new form Administrador
     */
    public Administrador(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        munAlta = new javax.swing.JMenuItem();
        munBaja = new javax.swing.JMenuItem();
        munConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        munDesconectar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Lineas");

        munAlta.setText("Alta");
        jMenu1.add(munAlta);

        munBaja.setText("Baja");
        jMenu1.add(munBaja);

        munConsulta.setText("Consulta");
        jMenu1.add(munConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Fin");

        munDesconectar.setText("Desconectar");
        jMenu2.add(munDesconectar);

        mnuSalir.setText("Salir");
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem munAlta;
    private javax.swing.JMenuItem munBaja;
    private javax.swing.JMenuItem munConsulta;
    private javax.swing.JMenuItem munDesconectar;
    // End of variables declaration//GEN-END:variables
}
